### PR TITLE
Added myself

### PR DESCRIPTION
**Pull request by sanketsahu**

### CODE REVIEW

**Review by geirman — COMMENTED** [review]
You should see if you can get on the RN Radio podcast too, Sanket

**Comment by sanketsahu** [comment]
@geirman Great! I will check that. Thanks!

**Comment by knowbody** [comment]
@sanketsahusoft can you please let me know on doodle when you're available? http://doodle.com/poll/rrwqm3dznw2msubf

**Comment by knowbody** [comment]
@sanketsahusoft hey could you email me so I can send you the details about tomorrows meetup, links, etc.
mateuszzatorski@gmail.com

**Pull request merged**
