### PR TITLE
Added proposal

### PR DESCRIPTION
**Pull request by panarasi**

### CODE REVIEW

**Comment by knowbody** [comment]
@panarasi can you please let me know on doodle when you're available? http://doodle.com/poll/rrwqm3dznw2msubf

**Comment by knowbody** [comment]
@panarasi are you still up for speaking on Thursday 8pm GMT time? please let me know

**Comment by panarasi** [comment]
@knowbody Sorry for the late response. Yes, I should be good for 8pm GMT - that is 1pm PST for me.

**Comment by knowbody** [comment]
amazing! see you on Thursday! I'll ping you the details later

**Comment by panarasi** [comment]
@knowbody Awesome, thanks

**Comment by knowbody** [comment]
@panarasi hey could you email me so I can send you the details about tomorrows meetup, links, etc.
mateuszzatorski@gmail.com

**Pull request merged**
