### PR TITLE
add Gant Laborde

### PR DESCRIPTION
**Pull request by GantMan**

### CODE REVIEW

**Comment by Monte9** [comment]
👍

**Comment by knowbody** [comment]
thank you!

**Comment by knowbody** [comment]
@GantMan could you please fill up the doodle http://doodle.com/poll/rrwqm3dznw2msubf

**Comment by GantMan** [comment]
Does doodle convert for timezones?

**Comment by knowbody** [comment]
It does

**Comment by knowbody** [comment]
@GantMan hey could you email me so I can send you the details about tomorrows meetup, links, etc.
mateuszzatorski@gmail.com

**Pull request merged**
